### ISSUE TITLE
library .so version change breaks rsyslog mmnormalize

### ISSUE THREAD

**Issue by davidelang** [rsyslog/liblognorm#126]
mmnormalize is looking for version 2, compiling v2-experimental only creates a version 3 library

doing
ln -s /usr/lib/liblognorm.so.3.0.0 /usr/lib/liblognorm.so.2
makes things work again.

Is there actually a need for the new .so version given that it's now backwards compatible?

**Comment by rgerhards** [comment]
The API has changed in parts. Chnage the version to 2 maybe it works...

Sent from phone, thus brief.
Am 05.08.2015 16:15 schrieb "davidelang" <notifications@github.com>:

**Comment by davidelang** [comment]
yes, making a link /usr/lib/liblognorm.so.2 that points at the new .3 library 
version works.

I believe that there's a way to define the .so versioning so that it knows that 
it can use the library for both .2 and .3 (so that things that need the new API 
can specify that they link against .3 while things that don't know about the 
change can link against .2 and hit the backwards compatibility code in .3)

David Lang

**Comment by rgerhards** [comment]
I have now checked the changes in more depth and wonder how rsyslog can work with the new code, because the API for loading rule bases has been removed and an improved on introduced with a new name. This is deliberately because they differ considerably. Even if rsyslog works, some other software will probably not, because another API has been completely removed without any replacement. See here: https://github.com/rsyslog/liblognorm/blob/v2-experimental/compatibility-v2

So we need to increase the major version number, see rules for the .so version here: http://www.gnu.org/software/libtool/manual/html_node/Updating-version-info.html

Please note that the compatibility layer is for rule bases. It is not a compatbility layer to make older software work with newer liblognorm without change. We can re-visit this decision in regard to ln_loadSamples(), but that would not change anything in regard to the .so version. So I wonder if that's something we need to change back. 

Note that I will be adapting rsyslog to the new liblognorm version shortly.

**Comment by rgerhards** [comment]
I just poked a bit more around. I change the API name deliberately as I assumed we would have no v1 ruleset compatibility, so there was no point in permitting apps to use everything unchanged. Now, this picture has changed. I could rename the API to ln_loadSamples() and add a dummy ln_loadSample(). The latter would always return an error. That way, the API would stay the same and existing apps would not need to be touched.

I sounds hackish, though. Any thoughts on that (@whissi maybe?).

**Comment by Whissi** [comment]
When an application **can** use `ln_loadSample()` at the moment replacing it with a function which will show a friendly error instead of causing breakage is not an option. The result will be the same: The application using *liblognorm* must be updated to keep working. If that's required, there's only one clean way: Change SONAME to break the application. That's the standard way to tell the world the software isn't compatible anymore. Something has changed, please review.

So please keep the changed SONAME. You can re-use `ln_loadSample()` due to the changed SONAME. Once *liblognorm-2* is ready I guess *mmnormalize* in *rsyslog* will be updated and you will raise the requirement to *liblognorm-2*.

For development you maybe want to keep the current SONAME and bump the SONAME when you bump the version to the final number when doing the release.

**Comment by davidelang** [comment]
Is there a way for existing apps to not have to change anything? the fact that rsyslog has been able to use the new version of the library without changes indicates that most things will work. what has to break and is there anyw ay to change it from a breakage to a wrapper?

with the v1 compatibility in the configs, what is it that cannot be supported by the new version?

**Comment by rgerhards** [comment]
@davidelang let me re-iterate that I do not really understand why existing rsyslog worked with v3. The ```ln_loadSamples()``` API that it uses is **not** present in the current v2-experimental branch. So in theory, it should not have loaded the lib due to missing symbol. Anyhow... as I wrote, I can probably go back to the old name, as the semantics of ```ln_loadRulebase``` and ```ln_loadSamples``` are identical (at least I think, need to check in detail). **However**, we need to realize that ```ln_loadSample()``` (without the "s") is no longer present, so according the rule for .soname versions, we need to increment the major number. While probably only few apps use that API, those that do will definitely break when being provided v2.

**Comment by rgerhards** [comment]
@davidelang it looks like I already changed the entry point name back to ln_loadSamples before I went to vacation. This is why the version worked for you. Will also keep it that way. Again, that doesn't meant we can keep the soname, the rest of the API changed. Just FYI.
