### ISSUE TITLE
using v2 lib with legacy config, parser cee-syslog behavior changes

### ISSUE THREAD

**Issue by davidelang** [rsyslog/liblognorm#128]
in the old version @cee:{json}stuff would match

rule=:%name:cee-syslog%stuff

with the new version, it doesn't match

remove the @cee: and java will match, but the cee-syslog doesn't tolerate the extra stuff at the end

the v2 documentation says this is the expected behaviour, but I don't think the parser should be this picky. I am trying to receive some log messages sent from nxlog on windows, and unfortunately it sends \r\n at the end of the line, not just \n. but in v1 a rule ending in %json;cee-syslog%#015 takes care of the problem

This is a common theme, you are trying hard to make sure that a parser doesn't match when it shouldn’t, that you are blocking cases where it would be useful for the parser to match as much as it can and leave the rest. If the parser really is the only way to tell two logs apart, this can be useful, but the vast majority of the time, if the parser doesn't match as much as is expected, the literals on the rule aren't going to match so you are still safe.

In v2 mode there may be a parameter to adjust this sensitivity, but in v1 mode the new parser shouldn’t be more strict than the v1 parser was.

**Comment by rgerhards** [comment]
I am not sure what "java will match" means (typo?), but if the old parsers accepted this, that was a bug in the old parser. This is so because cee clearly defines that **no data** is permitted after the JSON. This rule is part of the spec and it was introduced in order to avoid misinterpretation with legacy syslog (which we were very concerned about at that time). There is no point in arguing now if that was a smart decision or not, as this is not a rsyslog spec but one maintained by Mitre (or better said, no longer being updated by Mitre, so we can't even argue there).

**Comment by rgerhards** [comment]
I just double-checked. The cee-syslog parser was released for the first time in 1.1.2, and it contained the same restrictions from it's initial version: https://github.com/rsyslog/liblognorm/commit/22ae900f2a71deb476442c9ae23617e64c1ccb83

Maybe you used some interim devel version where this did not properly work? In any case, it's correct as it currently is.

**Comment by rgerhards** [comment]
side-note: the v1 "mode" is actually a *copy* of the v1 code. Check ./src/v1_parser.c -- it contains the exact code vom v2. The ./src/parser.c contains the new parsers. There was no way to do this without code duplication, because v1 and v2 are very different. With that said, v1 "mode" parses uses the exact same code base that 1.1.2 uses.

**Comment by davidelang** [comment]
to clarify what I was seeing

I have logs send to me by nxlog that are malformed in that it terminates the log with \r\n not \n, so they all show up ending with #015
with v1 I had

rule=:%json;cee-syslog%
that didn't match the rule, so I did
rule=:%json;cee-syslog%
rule=:%json;cee-syslog%#015
and this worked. When I built with the v2-experimetnal branch, this didn't work any longer. but the following rules did.
rule=:%json;cee-syslog%
rule=:@cee:%json;json%#015

it's very possible that I had been running some unreleased git snapshot for long enough to get tripped up.
