### ISSUE TITLE
only one user defined type works

### ISSUE THREAD

**Issue by rgerhards** [rsyslog/liblognorm#158]
From @davidelang :
```
type=@endpid:%{"type":"alternative","parser":[ {"type": "literal", "text":"]"},{"type": "literal", "text":"]:"} ] }%
type=@AUTOTYPE1:%iface:char-to:/%/%ip:ipv4%(%port:number%)
type=@AUTOTYPE1:%iface:char-to:\x3a%\x3a%ip:ipv4%/%port:number%
type=@AUTOTYPE1:%iface:char-to:\x3a%\x3a%ip:ipv4%/%port:number%
type=@AUTOTYPE1:%iface:char-to:\x3a%\x3a%ip:ipv4%
type=@AUTOTYPE1:%iface:char-to:\x3a%\x3a%ip:ipv4%
```

whichever I put first works, the second one doesn't.

**Comment by rgerhards** [comment]
Note that in the sample the alternative parser is ambigious, as "]" and "]:" both start with the same character. This would need priorities assigned to make it work reliably.

**Comment by davidelang** [comment]
On Mon, 9 Nov 2015, Rainer Gerhards wrote:

> Note that in the sample the alternative parser is ambigious, as "]" and "]:" 
> both start with the same character. This would need priorities assigned to 
> make it work reliably.


it should not need priorities set. This is like the superset problem

one message is

foo] bar

the other is

foo]: bar

only one of the two options will fit.

but in any case, the problem is that liblognorm reports that the second user 
type defined does not exist when you try to use it. you can swap the order of 
the two types being defined and it will switch which works and with throws an 
error.

David Lang

**Comment by rgerhards** [comment]
it's a bit off-topic, but: if you **explicitely** specify the *literal* parser, we include it into the same node. Thus, we now how two literals at the same tree node, and so we need to have priorities. The alternative would be to split the node in those cases, but then we would have problems if a name is assigned. Granted, then we could emit an error. Maybe we could create a feature request out of that description. For the current state, I think I'll document it. But we shouldn't work on that theme in this issue here, especially as it soon will be closed.
