### ISSUE TITLE
cisco-interface-spec at end of line

### ISSUE THREAD

**Issue by Amorik** [rsyslog/liblognorm#229]
When using the "cisco-interface-spec" field type if the interface is not followed by a space the returned array becomes null. I am presume this not intended behavior.

Sample Logs:
"outside:192.168.52.102/50349"
"outside:192.168.52.102/50349 outside:192.168.52.102/50349"
"outside:192.168.52.102/50349 "

Rule Base:
version=2
prefix=
rule=01:%interface1:cisco-interface-spec%
rule=02:%interface1:cisco-interface-spec% %interface2:cisco-interface-spec%
rule=03:%interface1:cisco-interface-spec%%-:whitespace%
rule=04:%interface1:cisco-interface-spec% %interface2:cisco-interface-spec%%-:whitespace%

Execution:
head sample.log | lognormalizer -r test.rb

Output:
{ "interface1": null }
{ "interface2": null, "interface1": { "interface": "outside", "ip": "192.168.52.102", "port": "50349" } }
{ "interface1": { "interface": "outside", "ip": "192.168.52.102", "port": "50349" } }

~Regards

**Comment by davidelang** [comment]
On Tue, 15 Nov 2016, Amorik wrote:

> When using the "cisco-interface-spec" field type if the interface is not followed by a space the returned array becomes null. I am presume this not intended behavior.

does Cisco actually output any logs that have this as the last element in the 
line (with no space after it)?

We really need to make a macro/function that accepts either a space or the end 
of the line and go through all the parsers in liblognorm and have them use it. 
There are several cases where people have been surprised that something doesn't 
match because the parser is looking for a space and doesn't find one at the end 
of the line.

IOW, I think it's within the spec of what we were trying to do, but it's 
probably not the best thing to do, and it's symtomatic of a problem we have in 
several places.

David Lang

> Sample Logs:
> "outside:192.168.52.102/50349"
> "outside:192.168.52.102/50349 outside:192.168.52.102/50349"
> "outside:192.168.52.102/50349 "
>
>
> Rule Base:
> version=2
> prefix=
> rule=01:%interface1:cisco-interface-spec%
> rule=02:%interface1:cisco-interface-spec% %interface2:cisco-interface-spec%
> rule=03:%interface1:cisco-interface-spec%%-:whitespace%
> rule=04:%interface1:cisco-interface-spec% %interface2:cisco-interface-spec%%-:whitespace%
>
>
> Execution:
> head sample.log | lognormalizer -r test.rb
>
> Output:
> { "interface1": null }
> { "interface2": null, "interface1": { "interface": "outside", "ip": "192.168.52.102", "port": "50349" } }
> { "interface1": { "interface": "outside", "ip": "192.168.52.102", "port": "50349" } }
>
> ~Regards
>
>

**Comment by Amorik** [comment]
The following is not a complete representation, I am not aware if there are more these just a few examples.

Examples of cisco messages ending in "cisco-interface-spec":
434002, 434003, 434007, 500004 

There are also some instances were "cisco-interface-spec" is followed by a period. Though it appears to be more of an issue of cisco optional output.
313005, 314001 

Cisco Message ID Documentation: http://www.cisco.com/c/en/us/td/docs/security/asa/syslog-guide/syslogs/logmsgs1.html 

~Regards

**Comment by rgerhards** [comment]
fixed by #298
